# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  name: MyPool

variables:
  tag: '$(Build.BuildId)'

steps:
- script: docker run --rm -v $(Build.SourcesDirectory)/tests-output:/tests andyfarkas/test-runner
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    searchFolder: '$(Build.SourcesDirectory)/tests-output'
