# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  name: MyPool

variables:
  tag: '$(Build.BuildId)'

steps:
- script: docker run --rm andyfarkas/test-runner
