# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
name: MyPool

resources:
  repositories: 
  - repository: self
  containers:
  - container: runner
    image: andyfarkas/test-runner

variables:
  tag: '$(Build.BuildId)'

steps:
- script: echo "I can run inside the container (it starts by default)"
  target:
    container: runner
