# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  name: MyPool

steps:
- script: docker run --rm -v $(Build.SourcesDirectory)/tests-output:/tests andyfarkas/test-runner
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    searchFolder: '$(Build.SourcesDirectory)/tests-output'
